### ISSUE TITLE
python3-pylint does not work

### ISSUE THREAD

**Issue by finn-cz** [msys2/MSYS2-packages#1636]
`pacman -Su mingw64/mingw-w64-x86_64-python3-pylint`
results in
```
pylint.exe
Traceback (most recent call last):
  File "D:\programs\msys64\mingw64\bin\pylint-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'`
```
After instalation of setuptools
`pacman -Sy mingw64/mingw-w64-x86_64-python3-setuptools`
pylint complains, that:
```
pylint.exe
Traceback (most recent call last):
  File "D:\programs\msys64\mingw64\bin\pylint-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "D:\programs\msys64\mingw64\lib\python3.7\site-packages\pkg_resources\__init__.py", line 3241, in <module>
    @_call_aside
  File "D:\programs\msys64\mingw64\lib\python3.7\site-packages\pkg_resources\__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "D:\programs\msys64\mingw64\lib\python3.7\site-packages\pkg_resources\__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "D:\programs\msys64\mingw64\lib\python3.7\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "D:\programs\msys64\mingw64\lib\python3.7\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\programs\msys64\mingw64\lib\python3.7\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typed-ast>=1.3.0' distribution was not found and is required by astroid
```

**Comment by peterbud** [comment]
You should post such issues to the https://github.com/msys2/MINGW-packages
