### ISSUE TITLE
Python doesn't load libraries when ran from vim

### ISSUE THREAD

**Issue by zingmars** [msys2/MSYS2-packages#1728]
Packages
```
vim 8.1.1777-1
python 3.7.4-1
```

I was trying to get https://github.com/davidhalter/jedi-vim to work, but for some reason it fails to load the required libraries. What's weirder, is that this only happens through vim.

After installing jedi using pip, I can run python and import jedi just fine -
```
$ python
Python 3.7.4 (default, Aug 15 2019, 18:17:27)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi
<module 'jedi' from 'C:/msys/mingw64/lib/python3.7/site-packages\\jedi\\__init__.py'>
```

However, when running `py3 import jedi` inside vim, I get the following error - 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mingw64/lib/python3.7/site-packages/jedi/__init__.py", line 38, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/mingw64/lib/python3.7/site-packages/jedi/api/__init__.py", line 16, in <module>
    import parso
  File "/mingw64/lib/python3.7/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/mingw64/lib/python3.7/site-packages/parso/parser.py", line 26, in <module>
    from parso import tree
  File "/mingw64/lib/python3.7/site-packages/parso/tree.py", line 3, in <module>
    from parso._compatibility import utf8_repr, encoding, py_version
  File "/mingw64/lib/python3.7/site-packages/parso/_compatibility.py", line 6, in <module>
    import platform
  File "/mingw64/lib/python3.7/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/mingw64/lib/python3.7/subprocess.py", line 152, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'
```

Any ideas why this could be happening?

**Comment by StarWolf3000** [comment]
Don't mix MSYS2 and MINGW environments. You're invoking the wrong Python.

**Comment by zingmars** [comment]
Huh, I had accidentally started the mingw shell instead of msys shell. My fault.

**Comment by urbster1** [comment]
What if one wants to use the mingw shell? I'm having a similar issue
