### ISSUE TITLE
[BUG] gradle-6.3-1 broken

### ISSUE THREAD

**Issue by pfusik** [msys2/MSYS2-packages#1913]
## Describe the bug

The package gradle-6.3-1 is broken. I've been using previous versions for months without problems.

## Steps to Reproduce the Problem

1. Run `pacman -S gradle`
2. Run `gradle`
3. The unexpected output is:

```
java.lang.IllegalArgumentException: Cannot find JAR 'asm-7.1.jar' required by module 'gradle-launcher' using classpath or distribution directory 'C:\msys64\usr\share\java\gradle'
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.findDependencyJar(DefaultModuleRegistry.java:316)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.findDependencyJars(DefaultModuleRegistry.java:183)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.module(DefaultModuleRegistry.java:173)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadOptionalModule(DefaultModuleRegistry.java:153)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadModule(DefaultModuleRegistry.java:137)
        at org.gradle.api.internal.classpath.DefaultModuleRegistry.getModule(DefaultModuleRegistry.java:117)
        at org.gradle.api.internal.DefaultClassPathProvider.findClassPath(DefaultClassPathProvider.java:31)
        at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(DefaultClassPathRegistry.java:35)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:49)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
```

Expected behavior: No missing jar error.

## Additional Context: Operating System, Screenshots

- OS: Windows 10 Home version 1903 64bit

**Comment by lazka** [comment]
@sal0max do you have an idea? I see you did older updates of gradle.

**Comment by lazka** [comment]
Things look fine here:

```
$ JAVA_HOME=java11 gradle

> Task :help

Welcome to Gradle 6.3.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

For troubleshooting, visit https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 698ms
1 actionable task: 1 executed
```

**Comment by sal0max** [comment]
Working just fine for me, too, after the update:

```
$ gradle tasks

Welcome to Gradle 6.3!

here are the highlights of this release:
 - Java 14 support
 - Improved error messages for unexpected failures

For more details see https://docs.gradle.org/6.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
...
```

I know that the gradle update can cause trouble if a gradle daemon is still running during update. That causes a lock on some files, the update is incomplete and leads to strange error messages like above.

The quick solution in this case is, to `rm -r` the gradle installation (should be in `/usr/share/java/gradle`) and re-install it through pacman.

Maybe the install script should be extended by something like the `gradle --stop` command, to be sure no locks are present.

**Comment by pfusik** [comment]
I tried reinstalling with pacman before submitting this ticket.
Tried now with `rm -r /usr/share/java/gradle` and it works!
Thanks a lot, you are doing great job!
