### ISSUE TITLE
[BUG] Segmentation fault when launching flexc++ or bisonc++

### ISSUE THREAD

**Issue by nerbug** [msys2/MSYS2-packages#2029]
## Describe the bug

Launching flexc++ or bisonc++ causes them to terminate with a segmentation fault and a core dump.

## Steps to Reproduce the Problem

1. Install flexc++ and bisonc++ from the repo
2. Launch flexc++ or bisonc++ with `flexc++` or `bisonc++` respectively

Expected behavior: flexc++ and bisonc++ should launch successfully.

## Additional Context: Operating system, core dumps

- OS: Windows 10 Pro 64-bit, version 2004, build 19041.329
- `flexc++` core dump:

```
Exception: STATUS_ACCESS_VIOLATION at rip=00423E4282E
rax=0000000423EABCA0 rbx=00000000FFFFCA50 rcx=00000001802675F0
rdx=0000000000000000 rsi=00000000FFFFCA58 rdi=00000000FFFFCA68
r8 =0000000800015630 r9 =00000000FFFFC8D0 r10=0000000100000000
r11=0000000423E47429 r12=0000000000000000 r13=00000000FFFFCA70
r14=00000000FFFFCB18 r15=00000000FFFFCA58
rbp=00000000FFFFCB16 rsp=00000000FFFFC8F0
program=C:\msys64\usr\bin\flexc++.exe, pid 2324, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFCB16  00423E4282E (001800D711C, 00180169918, 000FFFFC8F0, 000FFFFCA50)
000FFFFCB16  00423E47458 (000FFFFCB16, 00423E8C42C, 000FFFFCB28, 000FFFFCB20)
000FFFFCB16  00423E459DB (000FFFFCCE0, 00423E8CA12, 000FFFFCDF0, 000FFFFCA60)
000FFFFCB16  00423E46EA0 (00000000000, 00000000000, 00000000000, 000FFFFCB38)
000FFFFCB16  00423E460F4 (00423E88C00, 00000000000, 000FFFFCCE0, 001803502A0)
000FFFFCCE0  00423E83B00 (00000000000, 000FFFFCCE0, 001803502A0, 000FFFFCDF0)
000FFFFCCE0  00180058D33 (000FFFFCE00, 0000000002F, 001801C2616, 0018034FDF0)
000FFFFCCE0  00180058D61 (00000000000, 000FFFFCCE0, 0018029DBE0, 0018029DBE0)
000FFFFCCE0  0018005991F (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  00180049FCE (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```
- `bisonc++` core dump:
```
Exception: STATUS_ACCESS_VIOLATION at rip=00423E4282E
rax=0000000423EABCA0 rbx=00000000FFFFCA50 rcx=00000001802675F0
rdx=0000000000000000 rsi=00000000FFFFCA58 rdi=00000000FFFFCA68
r8 =0000000800015630 r9 =00000000FFFFC8D0 r10=0000000100000000
r11=0000000423E47429 r12=0000000000000000 r13=00000000FFFFCA70
r14=00000000FFFFCB18 r15=00000000FFFFCA58
rbp=00000000FFFFCB16 rsp=00000000FFFFC8F0
program=C:\msys64\usr\bin\bisonc++.exe, pid 2325, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFCB16  00423E4282E (001800D711C, 00180169918, 000FFFFC8F0, 000FFFFCA50)
000FFFFCB16  00423E47458 (000FFFFCB16, 00423E8C42C, 000FFFFCB28, 000FFFFCB20)
000FFFFCB16  00423E459DB (000FFFFCCE0, 00423E8CA12, 000FFFFCDF0, 000FFFFCA60)
000FFFFCB16  00423E46EA0 (00000000000, 00000000000, 00000000000, 000FFFFCB38)
000FFFFCB16  00423E460F4 (00423E88C00, 00000000000, 000FFFFCCE0, 0018034CE20)
000FFFFCCE0  00423E83B00 (00000000000, 000FFFFCCE0, 0018034CE20, 000FFFFCDF0)
000FFFFCCE0  00180058D33 (000FFFFCE00, 0000000002F, 001801C2616, 0018034FDF0)
000FFFFCCE0  00180058D61 (00000000000, 000FFFFCCE0, 0018029DBE0, 0018029DBE0)
000FFFFCCE0  0018005991F (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  00180049FCE (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

**Comment by lazka** [comment]
```
Thread 1 "flexc++" received signal SIGSEGV, Segmentation fault.
0x0000000423e4282e in msys-bobcat!_ZN3FBB8DateTime7resetTZEv () from /usr/bin/msys-bobcat.dll
(gdb) bt
#0  0x0000000423e4282e in msys-bobcat!_ZN3FBB8DateTime7resetTZEv () from /usr/bin/msys-bobcat.dll
#1  0x0000000423e47458 in msys-bobcat!_ZN3FBB8DateTime4Zone11zoneSecondsERKSs () from /usr/bin/msys-bobcat.dll
#2  0x0000000423e459db in msys-bobcat!_ZN3FBB8DateTime4Zone4dataERKSsSsSsSsSs () from /usr/bin/msys-bobcat.dll
#3  0x0000000423e46ea0 in msys-bobcat!_ZN3FBB8DateTime4Zone8storeIUOERKSsS3_S3_S3_S3_ () from /usr/bin/msys-bobcat.dll
#4  0x0000000423e460f4 in msys-bobcat!_ZN3FBB8DateTime4Zone10initializeEv () from /usr/bin/msys-bobcat.dll
#5  0x0000000423e83b00 in msys-bobcat!_ZTv0_n24_N3FBB7MstreamD1Ev () from /usr/bin/msys-bobcat.dll
#6  0x0000000180058d33 in per_module::run_ctors (this=this@entry=0x18034d090)
    at /msysdev/msys2-runtime/src/msys2-runtime/winsup/cygwin/dll_init.cc:188
#7  0x0000000180058d61 in dll::init (this=0x18034d080)
    at /msysdev/msys2-runtime/src/msys2-runtime/winsup/cygwin/dll_init.cc:219
#8  0x000000018005991f in dll::init (this=0x18034d080)
    at /msysdev/msys2-runtime/src/msys2-runtime/winsup/cygwin/dll_init.cc:612
#9  dll_list::init (this=<optimized out>) at /msysdev/msys2-runtime/src/msys2-runtime/winsup/cygwin/dll_init.cc:612
#10 0x0000000180049fce in dll_crt0_1 () at /msysdev/msys2-runtime/src/msys2-runtime/winsup/cygwin/dcrt0.cc:995
#11 0x0000000180048846 in _cygtls::call2 (this=0xffffce00, func=0x180049d20 <dll_crt0_1(void*)>, arg=0x0,
    buf=buf@entry=0xffffcdf0) at /msysdev/msys2-runtime/src/msys2-runtime/winsup/cygwin/cygtls.cc:40
#12 0x00000001800488f4 in _cygtls::call (func=<optimized out>, arg=<optimized out>)
    at /usr/include/w32api/psdk_inc/intrin-impl.h:790
#13 0x0000000000000000 in ?? ()

```
