### ISSUE TITLE
[BUG] Python 3.8.5 broken

### ISSUE THREAD

**Issue by jamietre** [msys2/MSYS2-packages#2050]
## Describe the bug

Python 3.8.5 breaks many things

## Steps to Reproduce the Problem

1. Upgrade from 3.8.4. to 3.8.5
2. `python3 -m pip install camelcase`
Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
  File "/usr/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 43, in <module>
    from pip._vendor import urllib3
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connection.py", line 68, in <module>
    class HTTPConnection(_HTTPConnection, object):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connection.py", line 96, in HTTPConnection
    default_socket_options = [(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)]
AttributeError: module 'socket' has no attribute 'TCP_NODELAY'
```

Running python "awslocal" script (python wrapper around aws cli):
```
'Namespace' object has no attribute 'cli_binary_format'
```

## Expected behavior: 

Python scripts work

Dowgrading to 3.8.4, everything works again.

## Additional Context: Operating System, Screenshots

- OS: [e.g. Windows 10 Pro version 1909 64bit]

I am not a python developer so I don't have a lot of context to troubleshoot or provide additional details; basically everything I use that depends on Python stopped working after I upgraded this morning.

[Edit] Quick way to downgrade:

```
pacman -U http://repo.msys2.org/msys/x86_64/python-3.8.4-1-x86_64.pkg.tar.zst
```

**Comment by alexeast99** [comment]
I'm having this problem as well. How did you downgrade to Python 3.8.4?

**Comment by alexeast99** [comment]
I'm not sure how you installed `pip` without also installing Python 3.8.5 as a dependency. I'm able to remove Python 3.8.5 and install Python 3.8.4, but when I install `python-pip` it reverts back to using Python 3.8.5. I would really appreciate some help!

**Comment by jamietre** [comment]
Hmm, it may be I never installed python-pip package? I donwgraded by
pulling the previous version's file directly from the package repo and
installing it. I've used the "-m pip" module syntax for situations I needed
to use pip myself.

I know very little about the python ecosystem generally.. so I am probably
not much more help ..

**Comment by HammerSquirrel** [comment]
I was able to downgrade using this:

`pacman -U /var/cache/pacman/pkg/python-3.8.4-1-x86_64.pkg.tar.zst
pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-python-pip-20.0.2-1-any.pkg.tar.xz`

If you don't have the old version of python in your local cache then just swap the link for the remote repo

**Comment by lazka** [comment]
The problem is that the latest msys2-runtime doesn't provide TCP_NODELAY anymore for some reason.

**Comment by lazka** [comment]
Because of https://github.com/msys2/Cygwin/commit/e037192b505b4f233fca9a6deafc9797210f6693

**Comment by lazka** [comment]
Potential fix: #2054

**Comment by jamietre** [comment]
Looks like the update has been published, works great again, thanks!

**Comment by lazka** [comment]
Yes, thanks for testing :)
