### ISSUE TITLE
Unable to resolve Windows path when using msys2/git

### ISSUE THREAD

**Issue by Lycolia** [msys2/MSYS2-packages#2840]
## Describe the issue

I can't use Git for Windows, so when I use msys2/git, I have a problem with the Windows path.

-   There are cases where Git for Windows freezes with zsh
    -   #2820
-   Unable to resolve Windows path when using msys2/git instead of Git for Windows
    -   This issue in [MkDocs](https://www.mkdocs.org/)

## Steps to Reproduce the Problem

1. `pacman -S git`
2. `mkdocs gh-deploy` in MkDocs Workspace
3. An following error occurs (Unable to resolve drive letters)

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\path\to\site
ERROR   -  [git-revision-date-localized-plugin] Unable to read git logs of 'D:\path\to\docs\file.md'.  To ignore this error, set option 'fallback_to_build_date: true'
ERROR   -  Error reading page 'file.md': Cmd('git') failed due to: exit code(128)
  cmdline: git log --date=short --format=%at -n 1 D:\path\to\docs\file.md
  stderr: 'fatal: invalid object name '"D'.'
Traceback (most recent call last):
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python39\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\mkdocs\__main__.py", line 176, in gh_deploy_command
    build.build(cfg, dirty=not clean)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\mkdocs\commands\build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\mkdocs\commands\build.py", line 167, in _populate_page
    page.markdown = config['plugins'].run_event(
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\mkdocs\plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\mkdocs_git_revision_date_localized_plugin\plugin.py", line 150, in on_page_markdown
    revision_dates = self.util.get_revision_date_for_file(
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\mkdocs_git_revision_date_localized_plugin\util.py", line 135, in get_revision_date_for_file
    raise err
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\mkdocs_git_revision_date_localized_plugin\util.py", line 107, in get_revision_date_for_file
    unix_timestamp = self._get_repo(realpath).log(
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\git\cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\git\cmd.py", line 1011, in _call_process
    return self.execute(call, **exec_kwargs)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\git\cmd.py", line 828, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git log --date=short --format=%at -n 1 D:\path\to\docs\file.md
  stderr: 'fatal: invalid object name '"D'.'
```

### Operation System

-   Windows 11 22000.469

### Terminal

-   VSCode 1.63.2
    -   settings.json
    ```json
    "terminal.integrated.defaultProfile.windows": "MSYS2",
    "terminal.integrated.profiles.windows": {
        "MSYS2": {
            "overrideName": true,
            "path": ["C:\\env\\msys64\\msys2_shell.cmd"],
            "args": [
                "-defterm",
                "-here",
                "-use-full-path",
                "-no-start",
                "-mingw64",
                "-shell",
                "zsh"
            ]
        },
    }
    ```

**Comment by Biswa96** [comment]
It seems that the command is not using mingw python, instead it picks another python installation. The path says that,

```
c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py
```

**Comment by Lycolia** [comment]
@Biswa96
Installing msys2/python improved the situation, but it still didn't help.
This does not happen if you are using Git for Windows, but Git for Windows doesn't work properly with msys2/zsh

-   Git for Windows + msys2/zsh
    -   There are cases where the terminal freezes
    -   MkDocs works correctly
-   msys2/git + msys2/zsh
    -   Terminal does not freeze
    -   MkDocs doesn't work properly
-   msys2/python3 + msys2/git + msys2/zsh
    -   Terminal does not freeze
    -   MkDocs doesn't work properly

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\Work\lycolia.info\note\site
ERROR   -  [git-revision-date-localized-plugin] Unable to read git logs of 'D:\path\to\docs\file.md'.  To ignore this error, set option 'fallback_to_build_date: true'
ERROR   -  Error reading page 'Golang\file.md': Cmd('git') failed due to: exit code(128)
  cmdline: git log --date=short --format=%at -n 1 D:\path\to\docs\file.md
  stderr: 'fatal: invalid object name '"D'.'
Traceback (most recent call last):
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
    unix_timestamp = self._get_repo(realpath).log(
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\git\cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\git\cmd.py", line 1011, in _call_process
    return self.execute(call, **exec_kwargs)
  File "c:\users\someuser\appdata\local\programs\python\python39\lib\site-packages\git\cmd.py", line 828, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git log --date=short --format=%at -n 1 D:\path\to\docs\file.md
  stderr: 'fatal: invalid object name '"D'.'
```

**Comment by lazka** [comment]
I'd guess the problem is that our git (unlike Git for Windows) can't deal with Windows paths.

**Comment by Lycolia** [comment]
Zsh freezes using Git for Windows, msys2/git can't resolve Windows paths.
I just want to see the current Git branch on Zsh's PS1, but I'm on a long journey because I can't do that

**Comment by Lycolia** [comment]
As a workaround, I solved it by using msys2/git only for the prompt part and using Git for Windows for the git command itself.
I think it's a bad way, so I think it would be better if there was a way for MSYS2 to call Git for Windows without any problems.

## Install method for msys2/git

```sh
pacman -S git
mv /usr/bin/git /usr/bin/msys2_git
```

## Prompt config

```sh
## git functions

current_git_branch() {
  (msys2_git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
}

parse_git_dirty() {
  local DIRTY=$(msys2_git status -s | tail -1)
  if [[ -n $DIRTY ]]; then
    echo "%{$fg_bold[magenta]%})%{$fg_bold[red]%}✗"
  else
    echo "%{$fg_bold[magenta]%})%{$fg_bold[blue]%}✓"
  fi
}

print_git_prompt() {
  local FIND_BRANCH=$(msys2_git branch 2> /dev/null | tail -1)
  if [[ -n $FIND_BRANCH ]]; then
    echo "%{$fg_bold[magenta]%}(%{$reset_color%}%{$fg_bold[yellow]%}"$(current_git_branch)$(parse_git_dirty)" %{$reset_color%} "
  else
    echo ""
  fi
}

## setting propmt

if [ "$USERNAME" = "root" ]; then
  CARETCOLOR="red";
else
  CARETCOLOR="magenta";
fi

PROMPT="
%{$fg_bold[cyan]%}%n%{$reset_color%}%{$fg_bold[blue]%}@%m%{$reset_color%}:%{${fg_bold[green]}%}%~%{$reset_color%}
%(?:%{$fg_bold[green]%}➜:%{$fg_bold[red]%}➜)  %{${reset_color}%}"'$(print_git_prompt)'

RPS1="%(?..%{$fg_bold[red]%} [ %? ]%{$reset_color%}) %D - %*"
```
