### ISSUE TITLE
[python] ssl package missing thus produce error once importing the package

### ISSUE THREAD

**Issue by RealYukiSan** [msys2/MSYS2-packages#4963]
### Description / Steps to reproduce the issue

install python with `pacman -S python` and run python script from [this gist](https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977)

### Expected behavior

successfully execute the script without error

### Actual behavior

an error occurs:
```
#  python.exe ./portable-msvc.py
Traceback (most recent call last):
  File "/home/ACER/./portable-msvc.py", line 108, in <module>
    manifest = json.loads(download(URL))
                          ^^^^^^^^^^^^^
  File "/home/ACER/./portable-msvc.py", line 35, in download
    with urllib.request.urlopen(url, context=ssl_context) as res:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 537, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ACER/./portable-msvc.py", line 110, in <module>
    import ssl
  File "/usr/lib/python3.12/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: No such process
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-26100

### Are you willing to submit a PR?

unfortunately I'm not sure how I should submit a PR as I don't know how to fix this

**Comment by RealYukiSan** [comment]
```bash
ACER@LAPTOP MSYS ~
# pacman -Ss '^python$'
msys/python 3.12.7-1 [installed]
    Next generation of the python high-level scripting language

ACER@LAPTOP MSYS ~
# pacman -Ss '^libopenssl$'
msys/libopenssl 3.3.2-1 (libraries) [installed: 3.2.0-1]
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security

ACER@LAPTOP MSYS ~
# pacman -Qi python
Name            : python
Version         : 3.12.7-1
Description     : Next generation of the python high-level scripting language
Architecture    : x86_64
URL             : https://www.python.org/
Licenses        : custom
Groups          : None
Provides        : python3
Depends On      : libbz2  libexpat  libffi  liblzma  ncurses  libopenssl  libreadline  mpdecimal  libsqlite  zlib  libxcrypt
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : python3
Installed Size  : 181.95 MiB
Packager        : CI (msys2/msys2-autobuild/cfdccd0a/11159009228)
Build Date      : Thu, Oct 3, 2024 4:03:54 PM
Install Date    : Tue, Oct 22, 2024 4:53:44 PM
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature


ACER@LAPTOP MSYS ~
# pacman -Qi libopenssl
Name            : libopenssl
Version         : 3.2.0-1
Description     : The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
Architecture    : x86_64
URL             : https://www.openssl.org
Licenses        : spdx:Apache-2.0
Groups          : libraries
Provides        : None
Depends On      : None
Optional Deps   : None
Required By     : bsdtar  heimdal-libs  openssl  python
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.35 MiB
Packager        : CI (msys2/msys2-autobuild/1ed7c15c/6991332791)
Build Date      : Sun, Nov 26, 2023 3:56:28 AM
Install Date    : Sat, Jan 13, 2024 5:28:49 PM
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by RealYukiSan** [comment]
re-installing the package solved the issue, I've no idea why lol, maybe the DB corrupt or smth.

but it solved anyway.
